xcodeproj 'PonApp/PonApp.xcodeproj'
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'PonApp' do
 	use_frameworks!
 	pod 'MBProgressHUD', '~> 1.0.0'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1.0'
    pod 'InstagramKit', '~> 3.0'
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'SnapKit', '~> 3.0'
    pod 'Google/Analytics'
end
