xcodeproj 'PonApp/PonApp.xcodeproj'
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'PonApp' do
 	use_frameworks!
 	pod 'MBProgressHUD', '~> 1.0.0'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1.0'
    pod 'SwiftyJSON'
#    pod 'ImageSlideshow', '~> 0.6'
#    pod 'DKImagePickerController', '~> 3.3.4'
#    pod 'SwiftQRCode'
    pod 'InstagramKit', '~> 3.0'
    pod 'Fabric'
    pod 'TwitterKit'
end
